USERROLES/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using USERROLES.Models;

namespace USERROLES.Controllers
{
    public class ExercisesController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Exercises
        public ActionResult Index()
        {
            var exercises = db.Exercises.Include(e => e.RX);
            return View(exercises.ToList());
        }

        // GET: Exercises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // GET: Exercises/Create
        public ActionResult Create()
        {
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName");
            return View();
        }

        // POST: Exercises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExID,ExName,ExDesc,ExPic1,ExPic2,ExPic3,ExPic4,ExVid,RxID,DurID")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                db.Exercises.Add(exercise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", exercise.RxID);
            return View(exercise);
        }

        // GET: Exercises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", exercise.RxID);
            return View(exercise);
        }

        // POST: Exercises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExID,ExName,ExDesc,ExPic1,ExPic2,ExPic3,ExPic4,ExVid,RxID,DurID")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exercise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", exercise.RxID);
            return View(exercise);
        }

        // GET: Exercises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // POST: Exercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exercise exercise = db.Exercises.Find(id);
            db.Exercises.Remove(exercise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

USERROLES/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using USERROLES.Models;

namespace USERROLES.Controllers
{
    public class LogsController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Logs
        public ActionResult Index()
        {
            var logs = db.Logs.Include(l => l.Patient).Include(l => l.Physician).Include(l => l.RX);
            return View(logs.ToList());
        }

        // GET: Logs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = db.Logs.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        // GET: Logs/Create
        public ActionResult Create()
        {
            ViewBag.PID = new SelectList(db.Patients, "PID", "PFName");
            ViewBag.PhID = new SelectList(db.Physicians, "PhID", "PhFName");
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName");
            return View();
        }

        // POST: Logs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LogID,LogTimeStamp,PainNumb,DiffNumb,ComTxt,IsComplete,FullSet,PartialSet,PID,PhID,RxID")] Log log)
        {
            if (ModelState.IsValid)
            {
                db.Logs.Add(log);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PID = new SelectList(db.Patients, "PID", "PFName", log.PID);
            ViewBag.PhID = new SelectList(db.Physicians, "PhID", "PhFName", log.PhID);
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", log.RxID);
            return View(log);
        }

        // GET: Logs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = db.Logs.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            ViewBag.PID = new SelectList(db.Patients, "PID", "PFName", log.PID);
            ViewBag.PhID = new SelectList(db.Physicians, "PhID", "PhFName", log.PhID);
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", log.RxID);
            return View(log);
        }

        // POST: Logs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LogID,LogTimeStamp,PainNumb,DiffNumb,ComTxt,IsComplete,FullSet,PartialSet,PID,PhID,RxID")] Log log)
        {
            if (ModelState.IsValid)
            {
                db.Entry(log).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PID = new SelectList(db.Patients, "PID", "PFName", log.PID);
            ViewBag.PhID = new SelectList(db.Physicians, "PhID", "PhFName", log.PhID);
            ViewBag.RxID = new SelectList(db.RXes, "RxID", "RxName", log.RxID);
            return View(log);
        }

        // GET: Logs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Log log = db.Logs.Find(id);
            if (log == null)
            {
                return HttpNotFound();
            }
            return View(log);
        }

        // POST: Logs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Log log = db.Logs.Find(id);
            db.Logs.Remove(log);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

USERROLES/Controllers/RXesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using USERROLES.Models;

namespace USERROLES.Controllers
{
    public class RXesController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: RXes
        public ActionResult Index()
        {
            return View(db.RXes.ToList());
        }

        // GET: RXes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RX rX = db.RXes.Find(id);
            if (rX == null)
            {
                return HttpNotFound();
            }
            return View(rX);
        }

        // GET: RXes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RXes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RxID,RxName,ExID,PID,PhID,LogID")] RX rX)
        {
            if (ModelState.IsValid)
            {
                db.RXes.Add(rX);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rX);
        }

        // GET: RXes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RX rX = db.RXes.Find(id);
            if (rX == null)
            {
                return HttpNotFound();
            }
            return View(rX);
        }

        // POST: RXes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RxID,RxName,ExID,PID,PhID,LogID")] RX rX)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rX).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rX);
        }

        // GET: RXes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RX rX = db.RXes.Find(id);
            if (rX == null)
            {
                return HttpNotFound();
            }
            return View(rX);
        }

        // POST: RXes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RX rX = db.RXes.Find(id);
            db.RXes.Remove(rX);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

USERROLES/Views/Exercises/Create.cshtml
@model USERROLES.Models.Exercise

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ExName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExVid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExVid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExVid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RxID, "RxID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RxID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RxID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DurID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DurID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DurID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

USERROLES/Views/Exercises/Delete.cshtml
@model USERROLES.Models.Exercise

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Exercise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExVid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExVid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DurID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DurID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RX.RxName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RX.RxName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

USERROLES/Views/Exercises/Details.cshtml
@model USERROLES.Models.Exercise

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
@Html.ActionLink("View Exercises", "Index", "Exercises")
@Html.ActionLink("View Logs", "Index", "Logs")
<div>
    <h4>Exercise</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ExName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExPic4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExPic4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExVid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExVid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DurID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DurID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RX.RxName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RX.RxName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ExID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

USERROLES/Views/Exercises/Edit.cshtml
@model USERROLES.Models.Exercise

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Exercise</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ExID)

        <div class="form-group">
            @Html.LabelFor(model => model.ExName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExPic4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExPic4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExPic4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExVid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExVid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExVid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RxID, "RxID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RxID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RxID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DurID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DurID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DurID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

USERROLES/Views/Exercises/Index.cshtml
@model IEnumerable<USERROLES.Models.Exercise>

@{
    ViewBag.Title = "Index";
}
@Html.ActionLink("View Exercises", "Index", "Exercises")
@Html.ActionLink("View RX's", "Index", "RXes")
<h2>Index</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ExName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExDesc)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExPic1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExPic2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExPic3)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExPic4)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExVid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DurID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RX.RxName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExPic1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExPic2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExPic3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExPic4)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExVid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DurID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RX.RxName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ExID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ExID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ExID })
            </td>
        </tr>
    }

</table>